name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Código
        uses: actions/checkout@v3

      - name: Instalar Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Rodar Testes
        run: npm test

      - name: Login no GitHub Container Registry
        run: docker build -t ghcr.io/${{ github.repository_owner }}/devops-lab:latest .
        
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository }}:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest